services:
  mc-forge:
    image: itzg/minecraft-server:java17
    container_name: minecraft-1.19.2
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods:/mods
      - ./config:/config
      - ./installers:/installers
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      MINECRAFT_VERSION: "1.19.2"
      FORGE_VERSION: "43.3.0"
      MEMORY: "4G"
      FORGE_INSTALLER: "/installers/forge-1.19.2-43.5.2-installer.jar"
    restart: unless-stopped
